services:
  - type: web
    name: estadisticas-futbol
    env: static
    buildCommand: ""
    startCommand: ""
    staticPublishPath: .
    headers:
      - path: /*
        name: Content-Security-Policy
        value: "default-src 'self' https:; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://unpkg.com https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; font-src 'self' https://cdnjs.cloudflare.com; connect-src 'self' https://mvsnymlcqutxnmnfxdgt.supabase.co"